name: Terraform Checks

on:
  workflow_call:
    inputs:
      run-apply:
        description: 'Whether or not to run terraform apply'
        required: false
        default: false
        type: boolean
      terraform-version:
        description: 'Version of terraform to use'
        required: true
        type: string
      iac-path:
        description: 'relative path to your IAC folder'
        required: false
        default: 'iac/develop'
        type: string
      cache-key-suffix:
        description: 'This workflow uses the actions/cache action to store the comment id so it can be updated on subsequent runs'
        required: false
        default: ''
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        description: 'AWS Access Key ID'
        required: true
      AWS_SECRET_ACCESS_KEY:
        description: 'AWS Secret Access Key'
        required: true
      TF_SECRETS:
        description: 'JSON formatted array of secrets to be injected into terraform'
        required: false
    outputs:
      terraform-outputs:
        description: "The outputs from terraform apply"
        value: ${{ jobs.terraform.outputs.terraform-outputs }}
jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    outputs:
      terraform-outputs: ${{ steps.plan.terraform-outputs }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Comment Id
        if: github.event_name == 'pull_request'
        id: cache-comment-id
        uses: actions/cache@v2.1.7
        with:
          path: ./comment-cache
          key: pr-${{ github.event.number }}-comment-id${{ inputs.cache-key-suffix }}

      - name: test cache
        run: |
            ls
            pwd
        
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.terraform-version }}
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: |
          cd ${{ inputs.iac-path }}
          terraform init
      - name: Terraform Validate
        id: validate
        run: |
          cd ${{ inputs.iac-path }}
          terraform validate -no-color
      - name: Terraform Plan
        id: plan
        run: |
          cd ${{ inputs.iac-path }}
          OUTPUT=$(terraform plan -no-color | sed -ne '/--------------------------------------------/,$ p')
          OUTPUT="${OUTPUT//'%'/'%25'}"
          OUTPUT="${OUTPUT//$'\n'/'%0A'}"
          OUTPUT="${OUTPUT//$'\r'/'%0D'}"

          echo "::set-output name=tf-plan::$OUTPUT"

        continue-on-error: true
      - name: Update PR Comment with Plan
        if: steps.cache-comment-id.outputs.cache-hit == 'true' && github.event_name == 'pull_request'
        id: update-pr-comment
        uses: actions/github-script@v5
        env:
          PLAN: "${{ steps.plan.outputs.tf-plan }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            console.log("Context: ")
            console.log(context)
            const fs = require('fs')
            let commentId = 0
            try {
              commentId = await fs.readFileSync('./comment-cache/comment-id', 'utf8')
            } catch (err) {
              console.log("err = " + err)
              return 
            }
            console.log("Comment Id: " + commentId)

            const output = `#### Terraform Checks for IAC Environment \`${{ inputs.iac-path }}\`
            #### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            <details>
            <summary>Show Plan</summary>
            \`\`\`\
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Auth: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
            github.rest.issues.updateComment({
               comment_id: commentId,
               owner: context.repo.owner,
               repo: context.repo.repo,
               body: output
            })
      - name: Create PR Comment with Plan
        if: steps.cache-comment-id.outputs.cache-hit != 'true' && github.event_name == 'pull_request'
        id: create-pr-comment
        uses: actions/github-script@v5
        env:
          PLAN: "${{ steps.plan.outputs.tf-plan }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            const output = `#### Terraform Checks for IAC Environment \`${{ inputs.iac-path }}\`
            #### Terraform Format and Style üñå\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ‚öôÔ∏è\`${{ steps.init.outcome }}\`
            #### Terraform Validation ü§ñ\`${{ steps.validate.outcome }}\`
            #### Terraform Plan üìñ\`${{ steps.plan.outcome }}\`
            <details>
            <summary>Show Plan</summary>
            \`\`\`\
            ${process.env.PLAN}
            \`\`\`
            </details>
            *Auth: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
             
            const result = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
            console.log('Create comment Comment Id: ' + result.data.id)
            return result.data.id
      - name: Terraform Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: test cache End
        run: |
            ls
            pwd
            mkdir -p comment-cache
            cd comment-cache
            echo ${{ steps.create-pr-comment.outputs.result }} > comment-id
            ls

      - name: Secrets to ENV
        if: ${{ inputs.run-apply }}
        shell: bash
        run: |
          for line in $(echo ${{ secrets.TF_SECRETS }} | jq -c '.[]' ); do
            name=$(echo $line | jq -r .name)
            value=$(echo $line | jq -r .value)
            echo "${name}=${value}" >> $GITHUB_ENV
          done

      - name: Terraform Apply
        id: apply
        if: ${{ inputs.run-apply }}
        shell: bash
        run: |
          cd ${{ inputs.iac-path }}

          terraform apply -auto-approve
          
          echo "::set-output name=terraform-outputs::$(terraform output -json)"
